name: Notas

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  add-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Adicionar Frase Aleatória
        run: |
          QUOTES=(
            "Keep learning! 🚀"
            "Automate everything! 🤖"
            "Debugging is like being a detective 🕵️‍♂️."
            "Cloud first, coffee second. ☁️☕"
            "The best code is no code at all. 💻✨"
            "Infrastructure as Code is the way. 📜☁️"
            "Think twice, code once. 🛠️"
            "Work smarter, not harder. 🧠⚡"
            "Containers are the future. 🐳🚀"
            "Logs never lie. 📜🔥"
          )
          RANDOM_QUOTE=${QUOTES[$RANDOM % ${#QUOTES[@]}]}

          if grep -q "### Atualizações Automáticas" README.md; then
            sed -i "/### Atualizações Automáticas/i \\\n$RANDOM_QUOTE\n" README.md
          else
            echo -e "\n$RANDOM_QUOTE" >> README.md
          fi

      - name: Data de Alteração
        run: |
          CURRENT_DATE=$(date +"%Y-%m-%d %H:%M:%S")
          if grep -q "### Atualizações Automáticas" README.md; then
            sed -i "s|- Alteração automática em .*|- Alteração automática em $CURRENT_DATE|g" README.md
          else
            echo -e "\n### Atualizações Automáticas\n- Alteração automática em $CURRENT_DATE" >> README.md
          fi

      - name: Commit & Push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN2 }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/luiscorreiaOps/luiscorreiaOps.git
          git add README.md
          git commit -m "Atualização: \"$RANDOM_QUOTE\" e data automática" || echo "Nada a commitar."
          git push origin main
